# Generated by Django 5.0.1 on 2024-01-29 11:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_staff_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=70, unique=True),
            preserve_default=False,
        ),
    ]
