# Generated by Django 5.0.1 on 2024-02-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='PNWebPushConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_web_push_enabled', models.BooleanField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=25, null=True)),
                ('position', models.CharField(blank=True, max_length=25, null=True)),
                ('bg_color', models.CharField(blank=True, max_length=25, null=True)),
                ('native_config', models.JSONField(blank=True, null=True)),
                ('box_config', models.JSONField(blank=True, null=True)),
                ('bell_config', models.JSONField(blank=True, null=True)),
                ('visibility_settings', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
