# Generated by Django 5.0.1 on 2024-02-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_pnwebpushconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pnwebpushconfig',
            name='is_web_push_enabled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
