# Generated by Django 5.0.1 on 2024-02-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_pnwebpushconfig_is_web_push_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnwebpushconfig',
            name='allow_button_text',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='pnwebpushconfig',
            name='badge_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pnwebpushconfig',
            name='dont_allow_button_text',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='pnwebpushconfig',
            name='icon_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pnwebpushconfig',
            name='opt_in_option',
            field=models.CharField(blank=True, choices=[('1', 1), ('2,', 2)], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='week',
            field=models.CharField(blank=True, choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=3, null=True),
        ),
    ]
